<a href="https://colab.research.google.com/github/CodeVerse-team/python-for-data-analysis-learning-libraries/blob/main/Numpy%20Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
n = 3

# PYTHON FOR DATA ANALYSIS

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
b = np.array([0, 0.5, 1, 1.5, 2])

Calling Eelements in Array 👇

In [ ]:
a[0], a[1], b[3]

(np.int64(1), np.int64(2), np.float64(1.5))

Same goes for the Slicing in python 👇

In [ ]:
a[0:]

array([1, 2, 3, 4])

In [ ]:
a[1:3]

array([2, 3])

In [ ]:
a[1:-1]

array([2, 3])

In [ ]:
a[::2]

array([1, 3])

In [ ]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

# Array Types

In [ ]:
b, a

(array([0. , 0.5, 1. , 1.5, 2. ]), array([1, 2, 3, 4]))

In [ ]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

In [ ]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [ ]:
b.dtype

dtype('float64')

In [ ]:
c = np.array(['a', 'b', 'c'])
c

array(['a', 'b', 'c'], dtype='<U1')

Numpy doesn't store stirngs or any other extra stuffs!

---

We Can Create Multi Dimensional Arrays in Numpy using python

In [ ]:
A = np.array([
    [1,2,3],
    [4,5,6],
])

In [ ]:
A.shape # shows the count of rows and column

(2, 3)

In [ ]:
A.ndim # ndim is no. of dimension in the matrix in vertical and horizontal terms

2

In [ ]:
A.size # size is a count of elements

6

In [ ]:
B = np.array([
    [
        [12,13,10],
        [9,7,8],
    ],
    [
        [6,7,8],
        [3,2,1]
    ]
])

In [ ]:
B

array([[[12, 13, 10],
        [ 9,  7,  8]],

       [[ 6,  7,  8],
        [ 3,  2,  1]]])

In [ ]:
B.shape

(2, 2, 3)

In [ ]:
B.ndim

3

In [ ]:
B.size

12

If the Shape isn't consistent, it'll just fall back to regular Python objects:

In [ ]:
Candy = np.array([
    [
        [12,11,14],
        [3,5,7],
    ],
    [
        [3,4,5],
        [3,4,5]
    ]
])

In [ ]:
Candy

array([[[12, 11, 14],
        [ 3,  5,  7]],

       [[ 3,  4,  5],
        [ 3,  4,  5]]])

In [ ]:
Candy.shape

(2, 2, 3)

# Indexing and Slicing of Matrices

In [ ]:
# Square Matrix
A = np.array([
   # 0 1 2
    [1,2,3], # 0
    [4,5,6], # 1
    [7,8,9]  # 2
])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A[1] # it by default selects the row.

array([4, 5, 6])

In [ ]:
A[1][0] # to select the first element of second row

np.int64(4)

In [ ]:
# we can pull this thing by multi dimensional selection of numpy
# A [d1, d2, d3, d4]
A[1,0]

np.int64(4)

In [ ]:
print("only brings 1st and 2nd row of matrix A")
A[0:2]

only brings 1st and 2nd row of matrix A


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print("Brings 1st and 2nd colum of all three rows from matrix A")
A[:, :2],

Brings 1st and 2nd colum of all three rows from matrix A


(array([[1, 2],
        [4, 5],
        [7, 8]]),)

In [ ]:
print("Brings first 2 elements from 1st and 2nd row")
A[:2, :2],

Brings first 2 elements from 1st and 2nd row


(array([[1, 2],
        [4, 5]]),)

In [ ]:
print("Taking the last column (index 2) from the first two rows")
A[:2, 2:]

Taking the last column (index 2) from the first two rows


array([[3],
       [6]])

# For Modification of an Array

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A[1] = np.array([10, 10, 10])
A
print(A, "\n\nThe above code modifies the value of 1st row and enters the new values as instructed")

[[ 1  2  3]
 [10 10 10]
 [ 7  8  9]] 

The above code modifies the value of 1st row and enters the new values as instructed


In [ ]:
print("This Below code tries to modify the 2nd row and last column of an element to change as 99.")
A[2,2] = 99
A

This Below code tries to modify the 2nd row and last column of an element to change as 99.


array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8, 99]])

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8, 99]])

# Summary Statistics
For one dimensional array

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a.sum()

np.int64(10)

In [ ]:
a.mean()

np.float64(2.5)

In [ ]:
a.std()

np.float64(1.118033988749895)

In [ ]:
a.var()

np.float64(1.25)

For Matrixes 👇

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8, 99]])

In [ ]:
A.sum()

np.int64(150)

In [ ]:
A.mean()

np.float64(16.666666666666668)

In [1]:
A.std()

NameError: name 'A' is not defined