<a href="https://colab.research.google.com/github/CodeVerse-team/python-for-data-analysis-learning-libraries/blob/main/Numpy%20Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [311]:
import numpy as np
import sys

In [312]:
n = 3

# PYTHON FOR DATA ANALYSIS

In [313]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [314]:
a = np.array([1,2,3,4])

In [315]:
b = np.array([0, 0.5, 1, 1.5, 2])

Calling Eelements in Array 👇

In [316]:
a[0], a[1], b[3]

(np.int64(1), np.int64(2), np.float64(1.5))

Same goes for the Slicing in python 👇

In [317]:
a[0:]

array([1, 2, 3, 4])

In [318]:
a[1:3]

array([2, 3])

In [319]:
a[1:-1]

array([2, 3])

In [320]:
a[::2]

array([1, 3])

In [321]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

# Array Types

In [322]:
b, a

(array([0. , 0.5, 1. , 1.5, 2. ]), array([1, 2, 3, 4]))

In [323]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

In [324]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [325]:
b.dtype

dtype('float64')

In [326]:
c = np.array(['a', 'b', 'c'])
c

array(['a', 'b', 'c'], dtype='<U1')

Numpy doesn't store stirngs or any other extra stuffs!

---

We Can Create Multi Dimensional Arrays in Numpy using python

In [327]:
A = np.array([
    [1,2,3],
    [4,5,6],
])

In [328]:
A.shape # shows the count of rows and column

(2, 3)

In [329]:
A.ndim # ndim is no. of dimension in the matrix in vertical and horizontal terms

2

In [330]:
A.size # size is a count of elements

6

In [331]:
B = np.array([
    [
        [12,13,10],
        [9,7,8],
    ],
    [
        [6,7,8],
        [3,2,1]
    ]
])

In [332]:
B

array([[[12, 13, 10],
        [ 9,  7,  8]],

       [[ 6,  7,  8],
        [ 3,  2,  1]]])

In [333]:
B.shape

(2, 2, 3)

In [334]:
B.ndim

3

In [335]:
B.size

12

If the Shape isn't consistent, it'll just fall back to regular Python objects:

In [336]:
Candy = np.array([
    [
        [12,11,14],
        [3,5,7],
    ],
    [
        [3,4,5],
        [3,4,5]
    ]
])

In [337]:
Candy

array([[[12, 11, 14],
        [ 3,  5,  7]],

       [[ 3,  4,  5],
        [ 3,  4,  5]]])

In [338]:
Candy.shape

(2, 2, 3)

# Indexing and Slicing of Matrices

In [339]:
# Square Matrix
A = np.array([
   # 0 1 2
    [1,2,3], # 0
    [4,5,6], # 1
    [7,8,9]  # 2
])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [340]:
A[1] # it by default selects the row.

array([4, 5, 6])

In [341]:
A[1][0] # to select the first element of second row

np.int64(4)

In [342]:
# we can pull this thing by multi dimensional selection of numpy
# A [d1, d2, d3, d4]
A[1,0]

np.int64(4)

In [343]:
print("only brings 1st and 2nd row of matrix A")
A[0:2]

only brings 1st and 2nd row of matrix A


array([[1, 2, 3],
       [4, 5, 6]])

In [344]:
print("Brings 1st and 2nd colum of all three rows from matrix A")
A[:, :2],

Brings 1st and 2nd colum of all three rows from matrix A


(array([[1, 2],
        [4, 5],
        [7, 8]]),)

In [345]:
print("Brings first 2 elements from 1st and 2nd row")
A[:2, :2],

Brings first 2 elements from 1st and 2nd row


(array([[1, 2],
        [4, 5]]),)

In [346]:
print("Taking the last column (index 2) from the first two rows")
A[:2, 2:]

Taking the last column (index 2) from the first two rows


array([[3],
       [6]])

# For Modification of an Array

In [347]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [348]:
A[1] = np.array([10, 10, 10])
A
print(A, "\n\nThe above code modifies the value of 1st row and enters the new values as instructed")

[[ 1  2  3]
 [10 10 10]
 [ 7  8  9]] 

The above code modifies the value of 1st row and enters the new values as instructed


In [349]:
print("This Below code tries to modify the 2nd row and last column of an element to change as 99.")
A[2,2] = 99
A

This Below code tries to modify the 2nd row and last column of an element to change as 99.


array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8, 99]])

In [350]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8, 99]])

# Summary Statistics
---
For one dimensional array 👇

In [351]:
a = np.array([1,2,3,4])

In [352]:
a.sum()

np.int64(10)

In [353]:
a.mean()

np.float64(2.5)

In [354]:
a.std()

np.float64(1.118033988749895)

In [355]:
a.var()

np.float64(1.25)

For Matrixes 👇

In [356]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8, 99]])

In [357]:
A.sum()

np.int64(150)

In [358]:
A.mean()

np.float64(16.666666666666668)

In [359]:
A.std()

np.float64(29.30301463444788)

In [360]:
A.sum(axis=0)

array([ 18,  20, 112])

In [361]:
A.sum(axis=1)

array([  6,  30, 114])

# Broadcasting and Vectorized Operations

In [362]:
ar = np.arange(4)

In [363]:
ar

array([0, 1, 2, 3])

In [364]:
ar + 10 # this operation does the addition, subtraction, multiplication and division to all the numbers in the value

array([10, 11, 12, 13])

In [365]:
ar * 10

array([ 0, 10, 20, 30])

In [366]:
ar

array([0, 1, 2, 3])

In [367]:
ar += 100

In [368]:
ar

array([100, 101, 102, 103])

In [369]:
l = [0,1,2,3]

In [370]:
[i*10 for i in l]

[0, 10, 20, 30]

In [371]:
a= np.arange(4)

In [372]:
a

array([0, 1, 2, 3])

In [373]:
b = np.array([10,10,10,10])

In [374]:
a + b

array([10, 11, 12, 13])

In [375]:
a*b

array([ 0, 10, 20, 30])

# Boolean Arrays
---
(Also Called as Masks)


In [376]:
a = np.arange(4)

In [377]:
a

array([0, 1, 2, 3])

In [378]:
a[[0, -1]]

array([0, 3])

In [379]:
a[[True, False, False, True]]
# this represent that in boolean terms we are only selecting the 1st and the last element in the arrays using True and false

array([0, 3])

In [380]:
a >= 2
# This shows that we are selecting and want to check in terms of boolean that we have a number that is greater than 2 is there or not.

array([False, False,  True,  True])

In [381]:
a[a >= 2]

array([2, 3])

In [382]:
a.mean()

np.float64(1.5)

In [383]:
a[a > a.mean()]

array([2, 3])

In [384]:
a[~(a > a.mean())]

array([0, 1])

In [385]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [386]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [387]:
A = np.random.randint(100, size = (3, 3))

In [388]:
A

array([[ 7, 24, 45],
       [20, 86,  7],
       [ 2, 97, 16]])

In [389]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([ 7, 45, 86,  2, 16])

In [390]:
A > 30

array([[False, False,  True],
       [False,  True, False],
       [False,  True, False]])

In [391]:
A[A > 30]

array([45, 86, 97])

# Linear Algebra
----
Below these all shows the operations using Dot Product, Transpose, Cross Product, Matrices all other stuffs.


In [392]:
A

array([[ 7, 24, 45],
       [20, 86,  7],
       [ 2, 97, 16]])

In [393]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [394]:
B

array([[6, 5],
       [4, 3],
       [2, 1]])

In [395]:
A.dot(B)
#

array([[228, 152],
       [478, 365],
       [432, 317]])

In [396]:
A @ B

array([[228, 152],
       [478, 365],
       [432, 317]])

In [397]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [398]:
A

array([[ 7, 24, 45],
       [20, 86,  7],
       [ 2, 97, 16]])

In [399]:
B.T @ A

array([[126, 682, 330],
       [ 97, 475, 262]])

# Size of Objects in Memory
---
## Int, Floats

In [400]:
# An Integer in Python is > 24 Bytes
sys.getsizeof(1)

28

In [401]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [402]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [403]:
# Numpy is much smaller
np.dtype(np.int8).itemsize

1

In [404]:
np.dtype(float).itemsize

8

# Lists are even larger

In [405]:
# A one - element list
sys.getsizeof([1])

64

In [406]:
# An array of one element in numpy
np.array([1]).nbytes

8

# And the Performance is also important

In [407]:
l = list(range(10000))

In [408]:
a = np.arange(10000)

In [409]:
%time np.sum(a ** 2)

CPU times: user 313 µs, sys: 0 ns, total: 313 µs
Wall time: 276 µs


np.int64(333283335000)

In [410]:
%time sum([x ** 2 for x in l])

CPU times: user 1.32 ms, sys: 31 µs, total: 1.35 ms
Wall time: 1.36 ms


333283335000

# Useful Numpy Functions


In [417]:
#Random
np.random.random(size=2)
np.random.normal(size=2)
np.randam.rand(2, 4)

array([0.78132827, 0.16675426])

In [ ]:
# Arange
np.arnage(10)
np.arange(5, 10)
np.arange(0, 1, -1)

In [ ]:
# Reshape
np.arange(10).reshape(2, 5)
np.arange(10).reshape(5, 2)

In [ ]:
# Linspace
np.linspace(0, 1, 5)
np.linspace(0, 1, 20)
np.linspace(0, 1, 20, False)

In [ ]:
# Zero's, Ones, Empty
np.zeros(5)
np.zeros((3, 3))
np.zeros((3, 3), dtype = np.int)
np.ones(5)
np.ones((3, 3))
np.empty(5)
np.empy(2, 2)

In [ ]:
# Identity and Eye
np.identity(4)
np.eye(3, 3)
np.eye(8, 4)
np.eye(8, 4, k=1)
np.eye(8, 4, k==3)
"Hello World" [6]