<a href="https://colab.research.google.com/github/CodeVerse-team/python-for-data-analysis-learning-libraries/blob/main/Numpy%20Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [5]:
n = 3

# PYTHON FOR DATA ANALYSIS

In [12]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [14]:
a = np.array([1,2,3,4])

In [15]:
b = np.array([0, 0.5, 1, 1.5, 2])

Calling Eelements in Array 👇

In [17]:
a[0], a[1], b[3]

(np.int64(1), np.int64(2), np.float64(1.5))

Same goes for the Slicing in python 👇

In [18]:
a[0:]

array([1, 2, 3, 4])

In [19]:
a[1:3]

array([2, 3])

In [20]:
a[1:-1]

array([2, 3])

In [21]:
a[::2]

array([1, 3])

In [22]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))